Fixed issue when gpio chip has no label (#35)
When a GPIO chip has no label, `gpiod.chip_iter()` leads to a
`IndexError` because the ioctl call leaves the label field empty, not
"\0":

![image](https://user-images.githubusercontent.com/57112334/232837059-231b9300-2dc4-4820-bac5-7c356570c306.png)

You can run the following python script when a GPIO chip has no label
```
import gpiod

chips_dict = {chip.name for chip in gpiod.chip_iter()}
print(chips_dict)
```
and it will result in:
```
Traceback (most recent call last):
  File "/home/pi/workspace/test.py", line 3, in <module>
    chips_dict = {chip.name for chip in gpiod.chip_iter()}
  File "/home/pi/.local/lib/python3.9/site-packages/gpiod/libgpiodcxx/__init__.py", line 1285, in __iter__
    self._iter = libgpiod.gpiod_chip_iter().__iter__()
  File "/home/pi/.local/lib/python3.9/site-packages/gpiod/libgpiod/__init__.py", line 1195, in __iter__
    chip = gpiod_chip_open(it)
  File "/home/pi/.local/lib/python3.9/site-packages/gpiod/libgpiod/__init__.py", line 127, in gpiod_chip_open
    if info.label[0] == "\0":
IndexError: index out of range
```

Whereas the gpiod cli handles the lable correctly:
```
$ gpiodetect
gpiochip0 [pinctrl-bcm2711] (58 lines)
gpiochip1 [raspberrypi-exp-gpio] (8 lines)
gpiochip2 [unknown] (2 lines)
```

Co-authored-by: Yacin Belmihoub-Martel <yacin.belmihoub-martel@silabs.com>